services:
  - type: web
    name: profile-analyzer
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    rootDir: .Profile_Analyzer_101
    envVars:
      - key: APIFY_API_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: true